services:
  api:
    build: .
    image: orderservice
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orderservice
      SPRING_DATASOURCE_USERNAME: orderservice
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: orderservice
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: orderservice
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderservice"]
      interval: 10s
      retries: 5