version: '3.8'

services:
  api:
    build: .
    image: orderservice
    container_name: orderservice_api
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: orderservice_db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
